name: iOS

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"
      - "*.png"
      - docs
      - app

concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: macos-11
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Prepare Xcode
        run: |
          xcodebuild -version
          swift --version

      - name: Build Shared
        run: ./gradlew :shared:build

      - name: Prepare Cocoapods
        run: |
          pod install
          xcodebuild -workspace iosApp.xcworkspace -scheme iosApp -destination "name=iPhone 12,platform=iOS Simulator,OS=latest" -configuration Debug -sdk iphonesimulator build
        working-directory: iosApp
